[package]
name = "morse-code-translator"
version = "0.1.0"
edition = "2021"

[lib]
name = "morse_code_translator"
path = "src/lib.rs"

[[bin]]
name = "morse_code_translator"
path = "src/main.rs"

[dependencies]
crossterm = "0.25"
